### ISSUE TITLE
Allow user to set amount of text to be generated

### ISSUE THREAD

**Issue by M0nica** [M0nica/greys-anatomy-lorem-ipsum-generator#3]
Given:
I am a user, I should be able to enter the number of paragraphs or words I would like generated

When:
I select number of paragraphs or words 

Then:
The output amount of text should match the amount of paragraphs or words that I selected.

<img width="725" alt="Screen Shot 2019-10-05 at 9 30 57 PM" src="https://user-images.githubusercontent.com/6998954/66262900-7f29fb80-e7b7-11e9-9cd3-4ef522f632b3.png">

**Comment by koslofse** [comment]
I submitted a pull request for this
https://github.com/M0nica/greys-anatomy-lorem-ipsum-generator/pull/4/files

**Comment by M0nica** [comment]
Thanks @koslofse! I left some comments and am looking forward to hearing your thoughts.

**Comment by M0nica** [comment]
This issue is still available to be worked on.

**Comment by yunior05** [comment]
Hey there 👋  I'd like to do this

**Comment by M0nica** [comment]
Okay, you can work on this issue @yunior05!

**Comment by yunior05** [comment]
@M0nica The PR is ready, check it when you can.
