### ISSUE TITLE
add button to copy text 

### ISSUE THREAD

**Issue by M0nica** [M0nica/greys-anatomy-lorem-ipsum-generator#9]
Consider using a clipboard library https://clipboardjs.com/

For example the copy button in this photo:
<img width="725" alt="Screen Shot 2019-10-05 at 9 30 57 PM" src="https://user-images.githubusercontent.com/6998954/66262969-c1a00800-e7b8-11e9-85e6-099ced49bb1f.png">

Given 
I click to generate lorem ipsum
generated text appears
I can click a button to copy all of the generated text into clipboard

**Comment by lulabromark** [comment]
I would be interested in working on this.

**Comment by yunior05** [comment]
Hey there I'd like to do this.

**Comment by ErisedKT** [comment]
Can I work on this?
